/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookConfirmedRouteImport } from './routes/book-confirmed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as ApiPublicConfirmBookingRouteImport } from './routes/api/public/confirm-booking'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedRoute = BookConfirmedRouteImport.update({
  id: '/book-confirmed',
  path: '/book-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreatmentsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicConfirmBookingRoute = ApiPublicConfirmBookingRouteImport.update({
  id: '/api/public/confirm-booking',
  path: '/api/public/confirm-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-confirmed': typeof BookConfirmedRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/book/$slug': typeof BookSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-confirmed': typeof BookConfirmedRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/book/$slug': typeof BookSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-confirmed': typeof BookConfirmedRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/book/$slug': typeof BookSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/api/public/confirm-booking': typeof ApiPublicConfirmBookingRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book-confirmed'
    | '/login'
    | '/team'
    | '/treatments'
    | '/admin/admins'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/team'
    | '/admin/treatments'
    | '/book/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/treatments/'
    | '/api/public/confirm-booking'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-confirmed'
    | '/login'
    | '/team'
    | '/admin/admins'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/team'
    | '/admin/treatments'
    | '/book/$slug'
    | '/treatments/$slug'
    | '/admin'
    | '/treatments'
    | '/api/public/confirm-booking'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book-confirmed'
    | '/login'
    | '/team'
    | '/treatments'
    | '/admin/admins'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/team'
    | '/admin/treatments'
    | '/book/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/treatments/'
    | '/api/public/confirm-booking'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookConfirmedRoute: typeof BookConfirmedRoute
  LoginRoute: typeof LoginRoute
  TeamRoute: typeof TeamRoute
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
  BookSlugRoute: typeof BookSlugRoute
  ApiPublicConfirmBookingRoute: typeof ApiPublicConfirmBookingRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-confirmed': {
      id: '/book-confirmed'
      path: '/book-confirmed'
      fullPath: '/book-confirmed'
      preLoaderRoute: typeof BookConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/confirm-booking': {
      id: '/api/public/confirm-booking'
      path: '/api/public/confirm-booking'
      fullPath: '/api/public/confirm-booking'
      preLoaderRoute: typeof ApiPublicConfirmBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookConfirmedRoute: BookConfirmedRoute,
  LoginRoute: LoginRoute,
  TeamRoute: TeamRoute,
  TreatmentsRoute: TreatmentsRouteWithChildren,
  BookSlugRoute: BookSlugRoute,
  ApiPublicConfirmBookingRoute: ApiPublicConfirmBookingRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
